name: Echo hello on self hosted

on: workflow_dispatch
jobs:
  deploy:
    environment:
      name: echo hi
    runs-on: nonprod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        run: echo hello
